# Generated by Django 5.2.14 on 2026-05-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('units', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(max_length=100)),
                ('subject_type', models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Laboratory'), ('lec_lab', 'Lecture + Lab')], default='lecture', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
