# Generated by Django 5.2.14 on 2026-05-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='schedule',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
