# Generated by Django 5.2.14 on 2026-05-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subject_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='instructor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
