# Generated by Django 5.2.14 on 2026-05-23 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_remove_section_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='room',
        ),
    ]
